"""Curated deterministic assessment fixtures for ProofPath MVP skills."""
from typing import Dict, List, Any

ASSESSMENT_FIXTURES: Dict[str, Dict[str, List[Dict[str, Any]]]] = {
    "Python": {
        "PRACTICAL": [
            {
                "id": "py_prac_1",
                "question": "Which of the following built-in collection types in Python is immutable?",
                "type": "MULTIPLE_CHOICE",
                "options": ["list", "dict", "tuple", "set"],
                "code_snippet": None,
                "correct_answer": "tuple",
                "explanation": "Tuples are immutable sequences; once created, their elements cannot be reassigned.",
                "points": 1.0,
            },
            {
                "id": "py_prac_2",
                "question": "What is the exact stdout output of this Python code snippet?",
                "type": "CODE_OUTPUT",
                "options": None,
                "code_snippet": "def mystery(nums):\n    return [x * 2 for x in nums if x % 2 != 0]\nprint(mystery([1, 2, 3, 4, 5]))",
                "correct_answer": "[2, 6, 10]",
                "explanation": "The list comprehension filters odd numbers (1, 3, 5) and multiplies each by 2.",
                "points": 1.0,
            },
            {
                "id": "py_prac_3",
                "question": "What is the evaluated integer value of len(set([1, 2, 2, 3, 3, 3, 4]))?",
                "type": "NUMERICAL_INPUT",
                "options": None,
                "code_snippet": None,
                "correct_answer": 4,
                "explanation": "A set eliminates duplicate elements, leaving {1, 2, 3, 4}, which has length 4.",
                "points": 1.0,
            },
            {
                "id": "py_prac_4",
                "question": "Which keyword is used in a try-block to catch and handle exceptions in Python?",
                "type": "MULTIPLE_CHOICE",
                "options": ["catch", "except", "handle", "rescue"],
                "code_snippet": None,
                "correct_answer": "except",
                "explanation": "Python uses 'try' and 'except' blocks for exception handling.",
                "points": 1.0,
            },
        ],
        "FOLLOW_UP": [
            {
                "id": "py_fu_1",
                "question": "In your Python project, why is using a context manager (`with open(...)`) preferred for file operations?",
                "type": "MULTIPLE_CHOICE",
                "options": [
                    "It automatically closes the file even if exceptions occur",
                    "It speeds up disk I/O significantly",
                    "It locks the file from being read by other OS processes",
                    "It encrypts file contents during read/write",
                ],
                "code_snippet": None,
                "correct_answer": "It automatically closes the file even if exceptions occur",
                "explanation": "Context managers implement __enter__ and __exit__ to guarantee resource cleanup.",
                "points": 1.0,
            },
            {
                "id": "py_fu_2",
                "question": "What is the exact stdout output of this Python code snippet?",
                "type": "CODE_OUTPUT",
                "options": None,
                "code_snippet": "x = [1, 2, 3]\ny = x\ny.append(4)\nprint(len(x))",
                "correct_answer": "4",
                "explanation": "y is assigned the same list reference as x, so appending to y mutates x.",
                "points": 1.0,
            },
            {
                "id": "py_fu_3",
                "question": "What is the average-case time complexity of looking up a key in a standard Python dictionary?",
                "type": "MULTIPLE_CHOICE",
                "options": ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
                "code_snippet": None,
                "correct_answer": "O(1)",
                "explanation": "Python dictionaries use hash tables which provide O(1) average lookup complexity.",
                "points": 1.0,
            },
        ],
    },
    "Pandas": {
        "PRACTICAL": [
            {
                "id": "pd_prac_1",
                "question": "Which Pandas function is primarily used to load tabular data from a CSV file into a DataFrame?",
                "type": "MULTIPLE_CHOICE",
                "options": ["pd.read_csv()", "pd.open_csv()", "pd.load_table()", "pd.DataFrame.from_csv()"],
                "code_snippet": None,
                "correct_answer": "pd.read_csv()",
                "explanation": "pd.read_csv() is the standard Pandas function for reading CSV data into a DataFrame.",
                "points": 1.0,
            },
            {
                "id": "pd_prac_2",
                "question": "What is the exact stdout output of this Pandas calculation?",
                "type": "CODE_OUTPUT",
                "options": None,
                "code_snippet": "import pandas as pd\ndf = pd.DataFrame({'a': [10, 20, 30]})\nprint(int(df['a'].mean()))",
                "correct_answer": "20",
                "explanation": "(10 + 20 + 30) / 3 = 20.0, cast to int gives 20.",
                "points": 1.0,
            },
            {
                "id": "pd_prac_3",
                "question": "How many rows are returned by df.head(7) if the DataFrame contains 50 rows?",
                "type": "NUMERICAL_INPUT",
                "options": None,
                "code_snippet": None,
                "correct_answer": 7,
                "explanation": "df.head(7) returns the first 7 rows of the DataFrame.",
                "points": 1.0,
            },
            {
                "id": "pd_prac_4",
                "question": "Which method drops rows with missing/null values from a DataFrame?",
                "type": "MULTIPLE_CHOICE",
                "options": ["df.dropna()", "df.remove_null()", "df.clean_na()", "df.pop_empty()"],
                "code_snippet": None,
                "correct_answer": "df.dropna()",
                "explanation": "df.dropna() filters out labels with missing values.",
                "points": 1.0,
            },
        ],
        "FOLLOW_UP": [
            {
                "id": "pd_fu_1",
                "question": "When aggregating data by category in Pandas, which method groups rows before applying an aggregation function like sum or mean?",
                "type": "MULTIPLE_CHOICE",
                "options": ["groupby()", "aggregate_by()", "cluster()", "pivot_table_only()"],
                "code_snippet": None,
                "correct_answer": "groupby()",
                "explanation": "groupby() splits the data into groups based on some criteria for aggregation.",
                "points": 1.0,
            },
            {
                "id": "pd_fu_2",
                "question": "What is the exact stdout output of this Pandas boolean mask summation?",
                "type": "CODE_OUTPUT",
                "options": None,
                "code_snippet": "import pandas as pd\ns = pd.Series([1, 2, 3, 4])\nprint((s > 2).sum())",
                "correct_answer": "2",
                "explanation": "Elements 3 and 4 satisfy s > 2, giving two True values; True.sum() evaluates to 2.",
                "points": 1.0,
            },
            {
                "id": "pd_fu_3",
                "question": "What is the primary difference between .loc and .iloc in Pandas?",
                "type": "MULTIPLE_CHOICE",
                "options": [
                    ".loc is label-based indexing while .iloc is integer position-based indexing",
                    ".loc is integer position-based while .iloc is label-based",
                    ".loc is for Series only while .iloc is for DataFrames only",
                    "There is no difference in indexing behavior",
                ],
                "code_snippet": None,
                "correct_answer": ".loc is label-based indexing while .iloc is integer position-based indexing",
                "explanation": ".loc indexes by explicit labels; .iloc indexes strictly by 0-based integer position.",
                "points": 1.0,
            },
        ],
    },
    "Matplotlib": {
        "PRACTICAL": [
            {
                "id": "mpl_prac_1",
                "question": "Which module in Matplotlib provides a MATLAB-like plotting interface?",
                "type": "MULTIPLE_CHOICE",
                "options": ["matplotlib.pyplot", "matplotlib.plots", "matplotlib.canvas", "matplotlib.figure"],
                "code_snippet": None,
                "correct_answer": "matplotlib.pyplot",
                "explanation": "matplotlib.pyplot is the standard collection of functions making Matplotlib work like MATLAB.",
                "points": 1.0,
            },
            {
                "id": "mpl_prac_2",
                "question": "What is the exact stdout output of this Matplotlib axes query?",
                "type": "CODE_OUTPUT",
                "options": None,
                "code_snippet": "import matplotlib.pyplot as plt\nfig, ax = plt.subplots(2, 2)\nprint(ax.size)",
                "correct_answer": "4",
                "explanation": "A 2x2 grid of subplots yields a 2D numpy array of 4 Axes objects.",
                "points": 1.0,
            },
            {
                "id": "mpl_prac_3",
                "question": "If plt.subplots(3, 4) is executed, how many total subplot axes are created?",
                "type": "NUMERICAL_INPUT",
                "options": None,
                "code_snippet": None,
                "correct_answer": 12,
                "explanation": "3 rows * 4 columns = 12 total subplot axes.",
                "points": 1.0,
            },
            {
                "id": "mpl_prac_4",
                "question": "Which function is called to display all active figure windows on screen?",
                "type": "MULTIPLE_CHOICE",
                "options": ["plt.show()", "plt.display()", "plt.render()", "plt.view()"],
                "code_snippet": None,
                "correct_answer": "plt.show()",
                "explanation": "plt.show() displays all open figures and starts the GUI event loop.",
                "points": 1.0,
            },
        ],
        "FOLLOW_UP": [
            {
                "id": "mpl_fu_1",
                "question": "Which function is used to save the active figure to an image or document file (e.g., PNG, SVG, PDF)?",
                "type": "MULTIPLE_CHOICE",
                "options": ["plt.savefig()", "plt.export_image()", "plt.write_fig()", "plt.store()"],
                "code_snippet": None,
                "correct_answer": "plt.savefig()",
                "explanation": "plt.savefig() saves the current figure to file.",
                "points": 1.0,
            },
            {
                "id": "mpl_fu_2",
                "question": "What is the exact stdout output of this Matplotlib figure cleanup snippet?",
                "type": "CODE_OUTPUT",
                "options": None,
                "code_snippet": "import matplotlib.pyplot as plt\nplt.clf()\nprint('cleared')",
                "correct_answer": "cleared",
                "explanation": "plt.clf() clears the current figure without error.",
                "points": 1.0,
            },
            {
                "id": "mpl_fu_3",
                "question": "In Matplotlib's object-oriented API, what does ax.set_xlabel('Time (s)') configure?",
                "type": "MULTIPLE_CHOICE",
                "options": [
                    "The label for the x-axis",
                    "The main title of the plot",
                    "The legend entry for the first line",
                    "The tick mark intervals",
                ],
                "code_snippet": None,
                "correct_answer": "The label for the x-axis",
                "explanation": "ax.set_xlabel sets the text label displayed along the horizontal x-axis.",
                "points": 1.0,
            },
        ],
    },
    "Git/GitHub": {
        "PRACTICAL": [
            {
                "id": "git_prac_1",
                "question": "Which command initializes a brand new Git repository in the current working directory?",
                "type": "MULTIPLE_CHOICE",
                "options": ["git init", "git new", "git create", "git start"],
                "code_snippet": None,
                "correct_answer": "git init",
                "explanation": "git init creates a new .git subdirectory with repository metadata.",
                "points": 1.0,
            },
            {
                "id": "git_prac_2",
                "question": "What Git command creates and immediately switches to a new branch called 'feature'?",
                "type": "MULTIPLE_CHOICE",
                "options": ["git checkout -b feature", "git branch --switch feature", "git new-branch feature", "git make feature"],
                "code_snippet": None,
                "correct_answer": "git checkout -b feature",
                "explanation": "git checkout -b <name> or git switch -c <name> creates and checks out the branch.",
                "points": 1.0,
            },
            {
                "id": "git_prac_3",
                "question": "How many parents does an initial (root) commit have in a standard Git repository?",
                "type": "NUMERICAL_INPUT",
                "options": None,
                "code_snippet": None,
                "correct_answer": 0,
                "explanation": "The initial commit in a repository has zero parent commits.",
                "points": 1.0,
            },
            {
                "id": "git_prac_4",
                "question": "Which command stages all modified and newly created files in the repository directory?",
                "type": "MULTIPLE_CHOICE",
                "options": ["git add .", "git stage all", "git commit --all", "git update"],
                "code_snippet": None,
                "correct_answer": "git add .",
                "explanation": "git add . stages all changes in the current directory and subdirectories.",
                "points": 1.0,
            },
        ],
        "FOLLOW_UP": [
            {
                "id": "git_fu_1",
                "question": "What is the primary purpose of a pull request (PR) on GitHub?",
                "type": "MULTIPLE_CHOICE",
                "options": [
                    "To propose, review, and discuss changes before merging into the base branch",
                    "To permanently delete historical commits",
                    "To clone a private repository without credentials",
                    "To bypass branch protection rules",
                ],
                "code_snippet": None,
                "correct_answer": "To propose, review, and discuss changes before merging into the base branch",
                "explanation": "Pull requests let you tell others about changes you've pushed to a branch in a repository on GitHub.",
                "points": 1.0,
            },
            {
                "id": "git_fu_2",
                "question": "What modern Git command discards uncommitted changes in the working tree for a specific file 'app.py'?",
                "type": "MULTIPLE_CHOICE",
                "options": ["git restore app.py", "git drop app.py", "git undo app.py", "git clear app.py"],
                "code_snippet": None,
                "correct_answer": "git restore app.py",
                "explanation": "git restore <file> discards working tree changes.",
                "points": 1.0,
            },
            {
                "id": "git_fu_3",
                "question": "What command downloads commits from a remote repository and immediately integrates them into the current local branch?",
                "type": "MULTIPLE_CHOICE",
                "options": ["git pull", "git fetch", "git push", "git remote update"],
                "code_snippet": None,
                "correct_answer": "git pull",
                "explanation": "git pull runs git fetch followed by git merge to update the active branch.",
                "points": 1.0,
            },
        ],
    },
}
